name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    container:
      image: perl:latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: cpanm ExtUtils::CBuilder
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: make test
        run: make test
